version: 2.1

orbs:
  node: circleci/node@3.0.0
  
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            node -v
            npm install mocha
            npm install
      - persist_to_workspace:
          root: .
          paths: 
            - .
  test_server:
      executor: node/default
      steps:
        - attach_workspace:
            at: .
        - checkout
        - run:
            name: Run Mocha tests
            command: npx mocha server.test.js
workflows:
  version: 2
  Test_Node_Server:
    jobs:
      - build
      - test_server:
          requires:
            - build
        
