version: 2.1

orbs:
  node: circleci/node@3.0.0
  
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            node -v
            npm install mocha
            npm install
            npm start
            echo 'Server started'
            sleep 2
            npx mocha server.test.js
