version: 2.1
jobs:
  Install:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            node -v
            npm install mocha
            npm install
  Start-Server:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Server starting
          command: |
            npm install mocha
            npm install
            BROWSER=chrome npm start
            echo 'Server started'
  Run-Tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            npm install mocha
            npm install
            sleep 15
            mocha server.test.js

workflows:
  version: 2
  Testing:
    jobs:
      - Install
      - Start-Server:
          requires:
            - Install
      - Run-Tests:
          requires:
            - Install
        
          
