version: 2.1

orbs:
  win: circleci/windows@2.2.0
  
jobs:
  Install:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    executor: 
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            node -v
            npm install mocha
            npm install
  Start-Server:
    steps:
      - checkout
      - run:
          name: Server starting
          command: |
            npm start
            echo 'Server started'
  Run-Tests:
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            sleep 2
            npx mocha server.test.js

workflows:
  version: 2
  Testing:
    jobs:
      - Install
      - Start-Server:
          requires:
            - Install
      - Run-Tests:
          requires:
            - Install
        
          
